---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-datadir
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /
    server: 192.168.0.21
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-datadir-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-pv-datadir
  storageClassName: ""
